default_install_hook_types: [pre-commit, prepare-commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
        language_version: python3.12
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: trailing-whitespace
  - repo: https://github.com/python/black
    rev: 23.10.1
    hooks:
      - id: black
        language_version: python3.12
        args: [--line-length=79]
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
